export const profile = {
  name: '윤우중',
  role: '웹 개발자',
  tagline: '서비스의 흐름을 이해하고, 끝까지 구현하는 웹 개발자.',
  intro:
    '프론트엔드의 사용자 경험부터 백엔드 기능과 운영 환경까지 폭넓게 고민합니다. React와 TypeScript를 중심으로 웹 서비스를 만들고, 배포 이후의 개선까지 책임집니다.',
  email: 'ywj98121791@gmail.com',
  phone: '010-4163-7540',
  location: '경기 화성시 반송동',
  birth: '1998년생 (만 27세)',
  availability: 'twentyoz 재직 중 · 주임 웹개발자',
  portfolio: 'https://developing-cell-df2.notion.site/1a1047c27d53806a9919fddc2791366f',
  links: [
    { label: 'GitHub', href: 'https://github.com/woojoung1217' },
    { label: 'Portfolio', href: 'https://developing-cell-df2.notion.site/1a1047c27d53806a9919fddc2791366f' },
    { label: 'Email', href: 'mailto:ywj98121791@gmail.com' },
  ],
  metrics: [
    { value: 'Web', label: 'Frontend & Backend' },
    { value: '3', label: 'SaaS Products' },
    { value: '1st', label: '장관상 수상' },
  ],
  facts: [
    { label: '현재', value: 'twentyoz 웹개발팀 주임' },
    { label: '학력', value: '순천향대학교 컴퓨터소프트웨어 졸업' },
    { label: '희망 직무', value: '웹 개발자 · 프론트엔드 개발자' },
    { label: '병역', value: '육군 병장 만기 제대' },
  ],
  experience: [
    {
      period: '2026. 03 — 재직 중',
      company: 'twentyoz (트웬티온즈)',
      role: '웹개발팀 · 주임 웹개발자',
      summary: '태양광 EMS 솔루션 운영·구축 지원 및 사내 서비스 개발',
      bullets: [
        '태양광 EMS P&ID 계통도와 설비 모니터링 화면 작화 및 운영',
        'InfoU 기반 태그 데이터 매핑·검증과 설비 데이터 구조 및 Modbus 태그 관리 지원',
        '사내 기술 블로그 Admin 기능 수정, 운영 화면 및 백엔드 개발',
        '고객 요구사항 반영과 운영 서버 배포·점검',
      ],
      tags: ['Web Development', 'Backend', 'EMS', 'InfoU', 'Modbus'],
      current: true,
    },
    {
      period: '2025. 06 — 2025. 09',
      company: '포그리트',
      role: '플랫폼개발팀 · 웹 개발자',
      summary: '웹 분석 SaaS와 사내 CRM의 프론트엔드 개발 및 유지보수',
      bullets: [
        'BAX 웹 접근성 분석 서비스의 Vue 3 UI와 캡처·HTML 코드 트리뷰 연동 기능 개발',
        'Vue i18n 기반 한·영·일 다국어 지원 및 TanStack Query를 활용한 서버 상태·캐싱 최적화',
        'Eagle M CRM의 고객·견적·결제 관리 기능 고도화와 PDF 견적서 자동 생성 구현',
        'Beusable UX 분석 서비스의 Canvas·Chart.js 기반 행동 데이터 시각화 및 Jira QA 참여',
      ],
      tags: ['Vue 3', 'TypeScript', 'TanStack Query', 'Canvas', 'Chart.js'],
    },
  ],
  projects: [
    {
      number: '01',
      title: 'BAX',
      category: '웹 접근성 분석 SaaS · 포그리트',
      description: 'URL만 입력하면 WCAG 표준에 따라 접근성을 자동 진단하고 문제 지점을 캡처 화면과 코드 트리에서 확인하는 서비스입니다.',
      detail: 'Vue 3 · i18n · TanStack Query',
      accent: 'violet',
    },
    {
      number: '02',
      title: 'Eagle M',
      category: '견적·결제 관리 CRM · 포그리트',
      description: '고객과 연락처, 견적, 결제 내역을 통합 관리하고 서비스별 산정 내역을 PDF 견적서로 생성하는 사내 시스템입니다.',
      detail: 'TypeScript · html2pdf · UI System',
      accent: 'orange',
    },
    {
      number: '03',
      title: 'Beusable',
      category: 'UX 분석 SaaS · 포그리트',
      description: '클릭과 스크롤, 이동 경로 데이터를 분석해 히트맵과 사용자 여정 리포트를 제공하는 UX 분석 플랫폼입니다.',
      detail: 'Canvas · Chart.js · Jira QA',
      accent: 'green',
    },
    {
      number: '04',
      title: 'Studio Matching',
      category: '스튜디오 매칭 플랫폼 · 멋쟁이사자처럼',
      description: '취향에 맞는 스튜디오 검색부터 예약과 촬영 일정 관리까지 하나의 흐름으로 연결한 맞춤형 플랫폼입니다.',
      detail: 'React · TypeScript · TDD',
      accent: 'blue',
    },
  ],
  activities: [
    {
      period: '2024. 10 — 2025. 01',
      title: '멋쟁이사자처럼 인턴',
      description: 'React와 TypeScript 기반 스튜디오 검색·예약 UI와 촬영 일정 관리 기능을 개발했습니다. 기획과 디자인부터 참여해 사용자 흐름을 설계하고, Jira 기반 협업과 UI 단위 테스트를 통해 사용성과 안정성을 개선했습니다.',
    },
    {
      period: '2023. 12 — 2024. 04',
      title: '테킷 프론트엔드 스쿨',
      description: '페이지 개발, 공통 컴포넌트, API 연동, 상태 관리, SSR, 무한 스크롤, 데이터 시각화와 배포·운영까지 실무 중심의 프론트엔드 과정을 수료했습니다.',
    },
    {
      period: '심화 과정',
      title: '멋쟁이사자처럼 프론트엔드 심화',
      description: 'Next.js 기반 AI 분석 서비스를 팀으로 개발하며 파일 업로드, GPT 결과 생성, 데이터 시각화, 위치 기반 기능과 성능 최적화를 구현했습니다.',
    },
  ],
  award: {
    year: '2024',
    title: '고용노동부 장관상',
    event: '제6회 K-디지털 트레이닝 해커톤',
    description: '저출산·고령사회 문제 해결을 위한 AI 기반 심리 케어 서비스를 개발했습니다. 난임 및 우울증 상담센터를 모바일로 전환하고 서비스 구조와 핵심 기능 개발을 주도해 기술적 완성도와 사회적 가치를 인정받았습니다.',
  },
  education: {
    period: '2017. 03 — 2023. 03',
    school: '순천향대학교',
    major: '컴퓨터소프트웨어 · 4년제 졸업',
  },
  skills: ['React', 'TypeScript', 'JavaScript', 'Vue.js', 'Next.js', 'NestJS', 'HTML5', 'CSS', 'MySQL', 'Git', 'GitLab'],
  introduction:
    '저는 협업과 소통을 기반으로 성장하는 웹 개발자입니다. 의견이 다를 때 상대의 생각을 먼저 경청하고 논리적인 타협점을 찾아 문제를 해결합니다. 코드 리뷰와 문서화로 팀이 같은 방향을 바라보게 만들고, 맡은 작업의 일정과 품질을 끝까지 책임집니다. React와 TypeScript 기반 개발에 익숙하며 웹 표준과 접근성을 고려한 UI부터 백엔드 기능, 배포와 운영까지 서비스 전체 흐름을 이해하고자 합니다. 단순히 작동하는 화면을 넘어 팀과 함께 성장하며 사용자에게 의미 있는 경험을 제공하는 개발자를 목표로 합니다.',
};
