export const profile = {
  name: '윤우중',
  role: '웹 개발자',
  tagline: '서비스의 흐름을 이해하고, 끝까지 구현하는 웹 개발자.',
  intro:
    '프론트엔드의 사용자 경험부터 백엔드 기능과 운영 환경까지 폭넓게 고민합니다. React와 TypeScript를 중심으로 웹 서비스를 만들고, 배포 이후의 개선까지 책임집니다.',
  email: 'ywj98121791@gmail.com',
  phone: '010-4163-7540',
  location: '경기 화성시 반송동',
  birth: '1998년생 (만 27세)',
  availability: 'twentyoz 재직 중 · 주임 웹개발자',
  portfolio: 'https://developing-cell-df2.notion.site/1a1047c27d53806a9919fddc2791366f',
  links: [
    { label: 'GitHub', href: 'https://github.com/woojoung1217' },
    { label: 'Portfolio', href: 'https://developing-cell-df2.notion.site/1a1047c27d53806a9919fddc2791366f' },
    { label: 'Email', href: 'mailto:ywj98121791@gmail.com' },
  ],
  metrics: [
    { value: 'Web', label: 'Frontend & Backend' },
    { value: '3', label: 'SaaS Products' },
    { value: '1st', label: '장관상 수상' },
  ],
  facts: [
    { label: '현재', value: 'twentyoz 웹개발팀 주임' },
    { label: '학력', value: '순천향대학교 컴퓨터소프트웨어 졸업' },
    { label: '희망 직무', value: '웹 개발자 · 프론트엔드 개발자' },
    { label: '병역', value: '육군 병장 만기 제대' },
  ],
  experience: [
    {
      period: '2026. 03 — 재직 중',
      company: 'twentyoz (트웬티온즈)',
      role: '웹개발팀 · 주임 웹개발자',
      summary: '태양광 EMS 서비스 풀스택 개발 및 현장 엔지니어링',
      bullets: [
        '태양광 발전소의 발전량·설비 상태·알람을 확인하는 EMS 모니터링 화면과 운영 기능을 프론트엔드부터 백엔드까지 개발',
        'P&ID 계통도와 인버터·접속반 등 설비별 상세 화면을 작화하고, 실시간 태그 데이터가 화면에 정확히 표현되도록 연동·검증',
        'InfoU 기반 설비 데이터 구조를 분석해 태그를 매핑하고 Modbus 주소, 데이터 타입, 스케일 등 통신 정보를 관리',
        '고객사 내부망 환경에 운영 서버를 배포하고 서버·클라이언트 간 접속, 설비 통신, 서비스 구동 상태를 점검',
        '현장 엔지니어링 과정에서 계통도·태그 목록과 실제 설비 데이터를 대조하고 오표기·통신 누락 사항을 수정',
        '고객 요구사항을 운영 화면과 기능에 반영하고 배포 이후 데이터·화면 이상 여부를 확인하며 서비스 안정화 지원',
        '사내 기술 블로그 Admin의 콘텐츠 관리 기능과 운영 화면을 수정하고 관련 백엔드 기능 개발',
      ],
      tags: ['React', 'TypeScript', 'JavaScript', 'NestJS', 'MySQL', 'EMS', 'InfoU', 'Modbus', 'Internal Network', 'GitLab'],
      current: true,
    },
    {
      period: '2025. 06 — 2025. 09',
      company: '포그리트',
      role: '플랫폼개발팀 · 웹 개발자',
      summary: '웹 분석 SaaS와 사내 CRM의 프론트엔드 개발 및 유지보수',
      bullets: [
        'BAX: Vue 3 Composition API 기반 진단 UI를 개발하고, 접근성 위반 위치를 캡처 이미지와 HTML 코드 트리에서 동시에 확인하도록 상태를 연동',
        'BAX: Vue i18n으로 한국어·영어·일본어를 지원하고 TanStack Query 캐싱을 적용해 중복 API 요청과 서버 상태 관리 복잡도를 개선',
        'Eagle M: 고객·연락처·회원·권한, 견적 생성 및 결제 내역 관리 기능을 고도화하고 html2pdf 기반 PDF 견적서 자동 생성 구현',
        'Eagle M: 반복 UI를 공통 컴포넌트로 정리하고 TypeScript 타입을 보강해 변경 영향 범위와 유지보수 비용을 축소',
        'Beusable: 스크롤 리포트 데이터를 Canvas와 Chart.js로 시각화하고 서비스 요구사항에 맞게 차트 렌더링을 커스터마이징',
        'Beusable: 배포 이후 유지보수와 Jira 기반 QA에 참여해 재현 조건 확인, 이슈 수정 및 회귀 점검 수행',
      ],
      tags: ['Vue 3', 'Composition API', 'TypeScript', 'Vue i18n', 'TanStack Query', 'Canvas', 'Chart.js', 'html2pdf', 'Jira'],
    },
  ],
  projects: [
    {
      number: '01',
      title: '태양광 EMS',
      category: '에너지 관리 시스템 · twentyoz',
      description: '태양광 발전 설비의 발전량, 운전 상태와 계통 흐름을 실시간으로 모니터링하는 서비스입니다. 프론트엔드·백엔드 기능 개발, P&ID 계통도 작화, InfoU·Modbus 태그 연동을 담당하며 고객사 내부망 배포와 설비 통신 점검, 현장 데이터 검증까지 수행하고 있습니다.',
      detail: 'React · TypeScript · NestJS · MySQL · InfoU · Modbus · 내부망 구축',
      accent: 'green',
    },
    {
      number: '02',
      title: 'BAX',
      category: '웹 접근성 분석 SaaS · 포그리트',
      description: 'URL 입력만으로 WCAG 기반 접근성 진단 결과를 제공하는 SaaS입니다. 위반 요소를 캡처 화면과 HTML 코드 트리뷰에 동시 표시하고, 한·영·일 다국어 지원 및 서버 상태 캐싱을 구현했습니다.',
      detail: 'Vue 3 · Composition API · TypeScript · Vue i18n · TanStack Query',
      accent: 'violet',
    },
    {
      number: '03',
      title: 'Eagle M',
      category: '견적·결제 관리 CRM · 포그리트',
      description: '고객·연락처·회원·권한과 견적·결제 내역을 통합 관리하는 사내 CRM입니다. 서비스별 가격과 산정 내역을 PDF 견적서로 자동 생성하고 공통 UI와 타입 구조를 개선했습니다.',
      detail: 'Vue · TypeScript · html2pdf · Component Design',
      accent: 'orange',
    },
    {
      number: '04',
      title: 'Beusable',
      category: 'UX 분석 SaaS · 포그리트',
      description: '클릭·스크롤·이동 경로를 분석해 히트맵과 사용자 여정 리포트를 제공하는 SaaS입니다. 스크롤 데이터를 기반으로 Canvas와 Chart.js 차트를 커스터마이징하고 배포 후 유지보수와 QA를 담당했습니다.',
      detail: 'Vue · TypeScript · Canvas · Chart.js · Jira',
      accent: 'green',
    },
    {
      number: '05',
      title: 'Studio Matching',
      category: '스튜디오 매칭 플랫폼 · 멋쟁이사자처럼',
      description: '취향에 맞는 스튜디오 검색부터 예약과 촬영 일정 관리까지 하나의 흐름으로 연결한 맞춤형 플랫폼입니다.',
      detail: 'React · TypeScript · TDD',
      accent: 'blue',
    },
  ],
  activities: [
    {
      period: '2024. 10 — 2025. 01',
      title: '멋쟁이사자처럼 인턴',
      description: 'React와 TypeScript 기반 스튜디오 검색·예약 UI와 촬영 일정 관리 기능을 개발했습니다. 기획과 디자인부터 참여해 사용자 흐름을 설계하고, Jira 기반 협업과 UI 단위 테스트를 통해 사용성과 안정성을 개선했습니다.',
    },
    {
      period: '2023. 12 — 2024. 04',
      title: '테킷 프론트엔드 스쿨',
      description: '페이지 개발, 공통 컴포넌트, API 연동, 상태 관리, SSR, 무한 스크롤, 데이터 시각화와 배포·운영까지 실무 중심의 프론트엔드 과정을 수료했습니다.',
    },
    {
      period: '심화 과정',
      title: '멋쟁이사자처럼 프론트엔드 심화',
      description: 'Next.js 기반 AI 분석 서비스를 팀으로 개발하며 파일 업로드, GPT 결과 생성, 데이터 시각화, 위치 기반 기능과 성능 최적화를 구현했습니다.',
    },
  ],
  award: {
    year: '2024',
    title: '고용노동부 장관상',
    event: '제6회 K-디지털 트레이닝 해커톤',
    description: '저출산·고령사회 문제 해결을 위한 AI 기반 심리 케어 서비스를 개발했습니다. 난임 및 우울증 상담센터를 모바일로 전환하고 서비스 구조와 핵심 기능 개발을 주도해 기술적 완성도와 사회적 가치를 인정받았습니다.',
  },
  education: {
    period: '2017. 03 — 2023. 03',
    school: '순천향대학교',
    major: '컴퓨터소프트웨어 · 4년제 졸업',
  },
  skills: ['React', 'TypeScript', 'JavaScript', 'Vue.js', 'Next.js', 'NestJS', 'HTML5', 'CSS', 'MySQL', 'Git', 'GitLab'],
  introduction:
    '저는 협업과 소통을 기반으로 성장하는 웹 개발자입니다. 의견이 다를 때 상대의 생각을 먼저 경청하고 논리적인 타협점을 찾아 문제를 해결합니다. 코드 리뷰와 문서화로 팀이 같은 방향을 바라보게 만들고, 맡은 작업의 일정과 품질을 끝까지 책임집니다. React와 TypeScript 기반 개발에 익숙하며 웹 표준과 접근성을 고려한 UI부터 백엔드 기능, 배포와 운영까지 서비스 전체 흐름을 이해하고자 합니다. 단순히 작동하는 화면을 넘어 팀과 함께 성장하며 사용자에게 의미 있는 경험을 제공하는 개발자를 목표로 합니다.',
};
